### PR TITLE
Build server application

### PR DESCRIPTION
**Pull request by ThomasWeiser**
- [x] Setup a node.js application...
- [x] that subscribes to clients' requests in Firebase
- [x] utilizing [firebase-queue](https://github.com/firebase/firebase-queue)
- [x] Process charges via Stripe API
- [x] Write result back to Firebase
- [x] Handle errors
- [x] ~~Ability to charge exiting customer's card again~~ (now in #16)

### CODE REVIEW

**Comment by ThomasWeiser** [comment]
This PR builds upon previous PR #12

**Comment by ThomasWeiser** [comment]
@romanzolotarev Please review the CI settings in `circle.yml`. The client code moved t its own directory `client/`. I have just done a quick hacking to adopt to this. It seems to pass but may not be the best way to do it.

**Comment by romanzolotarev** [comment]
All good. Merging.

By the way, @ThomasWeiser did you have a chance to look into http://package.elm-lang.org/packages/NoRedInk/elm-decode-pipeline/1.0.0/?

**Comment by ThomasWeiser** [comment]
> By the way, @ThomasWeiser did you have a chance to look into http://package.elm-lang.org/packages/NoRedInk/elm-decode-pipeline/1.0.0/?

Thanks for the hint. Integrated in #17

**Pull request merged**
