### PR TITLE
Read /shop from Firebase. Display name in header

### PR DESCRIPTION
**Pull request by ThomasWeiser**
A starting point for the Elm code.

* `Store/Shop.elm`  
    Read branch `/shop` once from Firebase
* `Component/Header.elm`  
    Display shop's name
* `Mail.elm`
    Standard glue code

### CODE REVIEW

**Comment by ThomasWeiser** [comment]
@romanzolotarev: In case you may want to review some first small steps

**Comment by romanzolotarev** [comment]
@ThomasWeiser Thanks. Let me review this on weekend.

**Comment by romanzolotarev** [comment]
@denisborovikov @ThomasWeiser Hey guys, you can integrate `elm-format` into your text editors or just run `elm-format --yes src` command via client-side git hook `pre-commit`.

- [neovim](https://github.com/romanzolotarev/dotfiles/blob/master/nvimrc#L52)
- [atom](https://atom.io/packages/elm-format)
- [sublime](https://packagecontrol.io/packages/Elm%20Language%20Support)

Thanks!

**Comment by romanzolotarev** [comment]
@ThomasWeiser everything works as expected. Shall we merge it?

**Comment by romanzolotarev** [comment]
@denisborovikov just FYI:

Use case: Change `shop/name` on Firebase and reload the page.

shop-header

**Comment by romanzolotarev** [comment]
Use case: Remove `shop/name` on Firebase and receive an error message in console after page reload.

shop-header2

**Comment by ThomasWeiser** [comment]
Ok, thanks for reviewing.

I see that you strongly prefer styling according to elm-format.
I will factor this in in my upcoming coding.

**Comment by romanzolotarev** [comment]
Thomas, thank you very much for understanding. If you prefer not to use `elm-format`, please do not. It is every easy to do later. Didn't want to distract you. :) Thanks again.

**Pull request merged**
