### PR TITLE
Add Circle CI integration

### PR DESCRIPTION
**Pull request by romanzolotarev**
- [x] cache `elm-stuff`
- [x] run `npm test` which just builds `Main.elm` for now

### CODE REVIEW

**Comment by ThomasWeiser** [comment]
Cannot say much here, because I have no experience with CircleCI.

Just a note about caching `eml-stuff`: Sometimes after updating `elm-package.json` the elm tools need to start with a fresh `elm-stuff`.

**Comment by romanzolotarev** [comment]
Thanks for the reminder. Turned cache off.

**Comment by ThomasWeiser** [comment]
CI server now complains: "No test commands were found".

**Comment by romanzolotarev** [comment]
@ThomasWeiser This is expected, because there is no `circle.yml` file in that branch. Let me merge this PR.

**Pull request merged**
