### PR TITLE
Contributing

### PR DESCRIPTION
**Pull request by romanzolotarev**
Add  [CONTRIBUTING.md](https://github.com/plentiful/shop/blob/contributing/CONTRIBUTING.md) with:
- [x] How we do PRs
- [x] How we style Elm
- [x] Note about licence
- [x] Note about documentation
- [x] Note about GitHub PR vs. Issues and labels

### CODE REVIEW

**Comment by romanzolotarev** [comment]
@denisborovikov @ThomasWeiser could you please review?

**Comment by denisborovikov** [comment]
:+1: Short and clear

**Comment by ThomasWeiser** [comment]
lgtm

Regarding Elm code style: While I agree with the general idiomatic styling of elm-format, I sometime prefer a more terse style. We will see. Feel free to reformat my code.

**Comment by romanzolotarev** [comment]
@ThomasWeiser We should fix `elm-format` then. ;)
Thanks guys. Merging.

**Pull request merged**
