### PR TITLE
Complete Checkout

### PR DESCRIPTION
**Pull request by ThomasWeiser**
* Header.elm
    * Sign-in button now scrolls to and focuses the email field of Checkout
    * Uses an outbound port to execute the DOM functions from JavaScript
* Catalog.elm
    * Show purchase state of items when signed-in
    * List gets class `signed-in`, items either class `paid` or `unpaid`
* New Store/Content.elm
    * Queries issue's content from Firebase
    * Code moved from Stage.elm to its own module
* Checkout.elm
    * Form validation executed immediately (by updating dependency `etaque/elm-simple-form` to verion 2.0.1)
    * Possible intents (of the user): signIn, signUp, resetPw, signUpAndBuy, newCardBuy, existingCardBuy
    * There is one Form (using etaque/simple-form) for all cases
    * The form has optional groups for those fields
    * Form is aware of customer model and issue model
    * The validation function checks all the cases
    * Effects for all intents
    * Simulate purchase for debugging purposes
* Stripe
    * Talks to Stripe.js via ports
    * Validation of card data fields
    * Generation of a credit card token
    * Further implementation needs some server-code
* Simpler way of passing down data
    * Shop name is now passed within a context to sub-components

### CODE REVIEW

**Comment by ThomasWeiser** [comment]
Memo to myself: 
The model of Checkout should probably use a ADT instead of a record.

**Comment by romanzolotarev** [comment]
@ThomasWeiser Thank you!
@denisborovikov Let's review this today.

**Comment by romanzolotarev** [comment]
> Stripe - Further implementation needs some server-code
@ThomasWeiser what would you recommend for hosting of the gateway? Heroku, AWS EC2, something else?

**Comment by romanzolotarev** [comment]
I like that Heroku can be deployed from CLI
https://devcenter.heroku.com/articles/getting-started-with-nodejs#set-up

**Comment by ThomasWeiser** [comment]
I wasn't into back end hacking for some time. So I cannot give a recommendation right now.

**Pull request merged**
